development:
  adapter:  mysql2
  encoding:  utf8
  database: prac
  username: root
  password:
#  database: <%= ENV['eTajara_DB_NAME'] %>
#  username: <%= ENV['eTajara_DB_USERNAME'] %>
#  password: <%= ENV['eTajara_DB_PASSWORD'] %>
